### ISSUE TITLE
Writing to pipe after pipe has been closed results in unhandled exception

### ISSUE THREAD

**Issue by johannesegger** [johannesegger/GetIt#1]
Doesn't always happen. It's more common if writes occur more frequently obviously.

```
Unhandled Exception: System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at GetIt.MessageProcessing.getMessageSender@427.Invoke(a msg) in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Common\Command.fs:line 434
   at System.Reactive.SynchronizedObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\SynchronizedObserver.cs:line 20
   at GetIt.MessageProcessing.sendCommand[a,b](ISubject`2 connection, a command) in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Common\Command.fs:line 479
   at GetIt.UICommunication.sendCommand(ControllerToUIMsg command) in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Controller\Controller.fs:line 231
   at GetIt.Game.ClearScene() in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Controller\Controller.fs:line 338
   at GetIt.Sample.Program.<>c__DisplayClass24_0.<Program22>b__15(ImmutableList`1 population, Int32 index) in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Sample\Program.cs:line 715
   at MoreLinq.MoreEnumerable.ForEach[T](IEnumerable`1 source, Action`2 action) in C:\projects\morelinq\MoreLinq\ForEach.cs:line 56
   at GetIt.Sample.Program.Program22() in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Sample\Program.cs:line 697
   at GetIt.Sample.Program.Main(String[] args) in C:\Users\egger\Workspace\GetIt.Fabulous\GetIt.Sample\Program.cs:line 39
```

**Comment by johannesegger** [comment]
fixed with f888f37
